<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SRResguardos.Application\SRResguardos.Application.csproj" />
    <ProjectReference Include="..\SRResguardos.Infrastructure\SRResguardos.Infrastructure.csproj" />
  </ItemGroup>

</Project>
